language: python
install:
    - pip install -r requirements.txt
branches:
    only:
        - master
script: coverage run manage.py test politikon
after_success:
    - coverage report
    - coveralls
