language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install .
    - pip install -r requirements.txt
branches:
    only:
        - master
before_script:
    - flake8
script: coverage run manage.py test politikon
after_success:
    - coverage report
    - coveralls
