language: python
install:
    - pip install -r requirements.txt
branches:
    only:
        - master
script: coverage run --source=politikon,events,accounts manage.py test --settings=politikon.settings.test
after_success:
    - coveralls
